#配置程序的启动端口号
server:
  port: 18081
#配置程序的服务名称(在eureka注册中心中注册的服务名称)和数据库连接信息
spring:
  application:
    name: goods-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/changgou_goods?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123666
#配置eureka注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
#配置feign的hystrix的熔断降级开启
feign:
  hystrix:
    enabled: true
#    使用通用mapper后这些配置可以不写，写了也无所谓
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#  mapper-locations: classpath:mapper/*Mapper.xml
#  type-aliases-package: com.changgou.goods.pojo

#配置输出sql语句
logging:
  level:
    com.fh.changgou.dao : debug